# Provides all dependent services

version: '3.6'

services:
  postgres:
    image: postgres:12.3-alpine
    volumes:
      - nmsdb:/var/lib/postgres/data
    environment:
      POSTGRES_DB: nms
      POSTGRES_USER: nms
      POSTGRES_PASSWORD: password
    restart: on-failure
    healthcheck:
      test: pg_isready

  nginx-proxy:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./docker/docker_ssl_proxy:/etc/nginx/conf.d
    depends_on:
      - magmalte

  magmalte:
    build:
      context: ../..
      dockerfile: fbcnms-projects/magmalte/Dockerfile
    command: "/usr/local/bin/wait-for-it.sh -s -t 30 postgres:5432 -- yarn run start:dev"
    volumes:
      - ../../fbcnms-packages:/usr/src/fbcnms-packages
      - ../../fbcnms-projects/magmalte/app:/usr/src/fbcnms-projects/magmalte/app
      - ../../fbcnms-projects/magmalte/scripts:/usr/src/fbcnms-projects/magmalte/scripts
      - ../../fbcnms-projects/magmalte/server:/usr/src/fbcnms-projects/magmalte/server
    depends_on:
      - postgres
    networks:
      - default
      - orc8r_default
    ports:
      - "8081:8081"
    environment:
      API_CERT_FILENAME: /run/secrets/api_cert
      API_PRIVATE_KEY_FILENAME: /run/secrets/api_key
      API_HOST: ${API_HOST:-proxy:9443}
      PORT: 8081
      HOST: 0.0.0.0
      MYSQL_HOST: postgres
      MYSQL_DB: nms
      MYSQL_USER: nms
      MYSQL_PASS: password
      MAPBOX_ACCESS_TOKEN: ${MAPBOX_ACCESS_TOKEN:-}
      MYSQL_DIALECT: postgres
    healthcheck:
      test: curl -If localhost:8081/healthz
    restart: on-failure
    secrets:
      - api_cert
      - api_key

secrets:
  api_cert:
    file: ${API_CERT_FILENAME:-../../../../.cache/test_certs/admin_operator.pem}
  api_key:
    file: ${API_PRIVATE_KEY_FILENAME:-../../../../.cache/test_certs/admin_operator.key.pem}

networks:
  orc8r_default:
    external: true

volumes:
  nmsdb:
